# Generated by Django 5.1.4 on 2024-12-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YieldCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('maturity', models.CharField(max_length=20)),
                ('yield_value', models.FloatField()),
            ],
        ),
    ]
