# Generated by Django 5.1.4 on 2024-12-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yieldcurve', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yieldcurve',
            name='maturity',
        ),
        migrations.RemoveField(
            model_name='yieldcurve',
            name='yield_value',
        ),
        migrations.AddField(
            model_name='yieldcurve',
            name='ytm_10y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yieldcurve',
            name='ytm_12m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yieldcurve',
            name='ytm_14d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yieldcurve',
            name='ytm_182d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yieldcurve',
            name='ytm_1d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yieldcurve',
            name='ytm_28d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yieldcurve',
            name='ytm_2y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yieldcurve',
            name='ytm_3y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yieldcurve',
            name='ytm_5y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yieldcurve',
            name='ytm_7d',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yieldcurve',
            name='ytm_7y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yieldcurve',
            name='ytm_91d',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
